### ISSUE TITLE
请问TextRank作为提取关键词算法的论文出处有吗？

### ISSUE THREAD

**Issue by IAmFQQ** [hankcs/TextRank#1]
我找到一篇名为：TextRank: Bringing Order into Texts

但里面的TextRank提取关键词的方法是以词性作为考量的，而您的算法是 权重是 1/连接总数，即所有和中心词连接的其他词均分这个影响力。 
请问你这么是按照这篇文章来的吗？还是按照其他文章来的？

**Comment by hankcs** [comment]
## 注意

**TextRank已经集成到[HanLP](https://github.com/hankcs/HanLP)中，本项目不再维护。**
